export const schema = gql`
  type Account {
    id: String!
    business_type: String
    charges_enabled: Boolean
    country: String
    created: DateTime
    default_currency: String
    details_submitted: Boolean
    email: String
    individual_id: String
    metadata: JSON
    object: String
    payouts_enabled: Boolean
    type: String
    deleted: Boolean
    tos_acceptance_date: DateTime
    tos_acceptance_ip: String
    tos_acceptance_service_agreement: String
    tos_acceptance_user_agent: String
    settings_bacs_debit_payments: JSON
    settings_branding: JSON
    settings_card_issuing: JSON
    settings_card_payments: JSON
    settings_dashboard: JSON
    settings_payments: JSON
    settings_payouts: JSON
    settings_sepa_debit_payments: JSON
    requirements_current_deadline: DateTime
    requirements_currently_due: [String]!
    requirements_disabled_reason: String
    requirements_errors: JSON
    requirements_eventually_due: [String]!
    requirements_past_due: [String]!
    requirements_pending_verification: [String]!
    business_profile_mcc: String
    business_profile_name: String
    business_profile_product_description: String
    business_profile_support_address: JSON
    business_profile_support_email: String
    business_profile_support_phone: String
    business_profile_support_url: String
    business_profile_url: String
    capabilities_acss_debit_payments: String
    capabilities_afterpay_clearpay_payments: String
    capabilities_au_becs_debit_payments: String
    capabilities_bacs_debit_payments: String
    capabilities_bancontact_payments: String
    capabilities_card_issuing: String
    capabilities_card_payments: String
    capabilities_cartes_bancaires_payments: String
    capabilities_eps_payments: String
    capabilities_fpx_payments: String
    capabilities_giropay_payments: String
    capabilities_grabpay_payments: String
    capabilities_ideal_payments: String
    capabilities_jcb_payments: String
    capabilities_legacy_payments: String
    capabilities_oxxo_payments: String
    capabilities_p24_payments: String
    capabilities_sepa_debit_payments: String
    capabilities_sofort_payments: String
    capabilities_tax_reporting_us_1099_k: String
    capabilities_tax_reporting_us_1099_misc: String
    capabilities_transfers: String
    company_address: JSON
    company_address_kana: JSON
    company_address_kanji: JSON
    company_directors_provided: Boolean
    company_executives_provided: Boolean
    company_name: String
    company_name_kana: String
    company_name_kanji: String
    company_owners_provided: Boolean
    company_phone: String
    company_structure: String
    company_tax_id_provided: Boolean
    company_tax_id_registrar: String
    company_vat_id_provided: Boolean
    company_verification: JSON
    person_account_individual_idToperson: Person
    application_fee: [ApplicationFee]!
    bank_account: [BankAccount]!
    capability: [Capability]!
    card: [Card]!
    charge_accountTocharge_destination_id: [Charge]!
    charge_accountTocharge_on_behalf_of_id: [Charge]!
    charge_accountTocharge_transfer_data_destination_id: [Charge]!
    connect_collection_transfer: [ConnectCollectionTransfer]!
    event: [Event]!
    invoice_accountToinvoice_on_behalf_of_id: [Invoice]!
    invoice_accountToinvoice_transfer_data_destination_id: [Invoice]!
    payment_intent_accountTopayment_intent_on_behalf_of_id: [PaymentIntent]!
    payment_intent_accountTopayment_intent_transfer_data_destination_id: [PaymentIntent]!
    person_accountToperson_account_id: [Person]!
    platform_tax_fee: [PlatformTaxFee]!
    recipient_accountTorecipient_migrated_to_id: [Recipient]!
    recipient_accountTorecipient_rolled_back_from_id: [Recipient]!
    setup_attempt: [SetupAttempt]!
    setup_intent: [SetupIntent]!
    subscription: [Subscription]!
    transfer: [Transfer]!
  }

  type Query {
    accounts: [Account!]!
  }

  input CreateAccountInput {
    business_type: String
    charges_enabled: Boolean
    country: String
    created: DateTime
    default_currency: String
    details_submitted: Boolean
    email: String
    individual_id: String
    metadata: JSON
    object: String
    payouts_enabled: Boolean
    type: String
    deleted: Boolean
    tos_acceptance_date: DateTime
    tos_acceptance_ip: String
    tos_acceptance_service_agreement: String
    tos_acceptance_user_agent: String
    settings_bacs_debit_payments: JSON
    settings_branding: JSON
    settings_card_issuing: JSON
    settings_card_payments: JSON
    settings_dashboard: JSON
    settings_payments: JSON
    settings_payouts: JSON
    settings_sepa_debit_payments: JSON
    requirements_current_deadline: DateTime
    requirements_currently_due: [String]!
    requirements_disabled_reason: String
    requirements_errors: JSON
    requirements_eventually_due: [String]!
    requirements_past_due: [String]!
    requirements_pending_verification: [String]!
    business_profile_mcc: String
    business_profile_name: String
    business_profile_product_description: String
    business_profile_support_address: JSON
    business_profile_support_email: String
    business_profile_support_phone: String
    business_profile_support_url: String
    business_profile_url: String
    capabilities_acss_debit_payments: String
    capabilities_afterpay_clearpay_payments: String
    capabilities_au_becs_debit_payments: String
    capabilities_bacs_debit_payments: String
    capabilities_bancontact_payments: String
    capabilities_card_issuing: String
    capabilities_card_payments: String
    capabilities_cartes_bancaires_payments: String
    capabilities_eps_payments: String
    capabilities_fpx_payments: String
    capabilities_giropay_payments: String
    capabilities_grabpay_payments: String
    capabilities_ideal_payments: String
    capabilities_jcb_payments: String
    capabilities_legacy_payments: String
    capabilities_oxxo_payments: String
    capabilities_p24_payments: String
    capabilities_sepa_debit_payments: String
    capabilities_sofort_payments: String
    capabilities_tax_reporting_us_1099_k: String
    capabilities_tax_reporting_us_1099_misc: String
    capabilities_transfers: String
    company_address: JSON
    company_address_kana: JSON
    company_address_kanji: JSON
    company_directors_provided: Boolean
    company_executives_provided: Boolean
    company_name: String
    company_name_kana: String
    company_name_kanji: String
    company_owners_provided: Boolean
    company_phone: String
    company_structure: String
    company_tax_id_provided: Boolean
    company_tax_id_registrar: String
    company_vat_id_provided: Boolean
    company_verification: JSON
  }

  input UpdateAccountInput {
    business_type: String
    charges_enabled: Boolean
    country: String
    created: DateTime
    default_currency: String
    details_submitted: Boolean
    email: String
    individual_id: String
    metadata: JSON
    object: String
    payouts_enabled: Boolean
    type: String
    deleted: Boolean
    tos_acceptance_date: DateTime
    tos_acceptance_ip: String
    tos_acceptance_service_agreement: String
    tos_acceptance_user_agent: String
    settings_bacs_debit_payments: JSON
    settings_branding: JSON
    settings_card_issuing: JSON
    settings_card_payments: JSON
    settings_dashboard: JSON
    settings_payments: JSON
    settings_payouts: JSON
    settings_sepa_debit_payments: JSON
    requirements_current_deadline: DateTime
    requirements_currently_due: [String]!
    requirements_disabled_reason: String
    requirements_errors: JSON
    requirements_eventually_due: [String]!
    requirements_past_due: [String]!
    requirements_pending_verification: [String]!
    business_profile_mcc: String
    business_profile_name: String
    business_profile_product_description: String
    business_profile_support_address: JSON
    business_profile_support_email: String
    business_profile_support_phone: String
    business_profile_support_url: String
    business_profile_url: String
    capabilities_acss_debit_payments: String
    capabilities_afterpay_clearpay_payments: String
    capabilities_au_becs_debit_payments: String
    capabilities_bacs_debit_payments: String
    capabilities_bancontact_payments: String
    capabilities_card_issuing: String
    capabilities_card_payments: String
    capabilities_cartes_bancaires_payments: String
    capabilities_eps_payments: String
    capabilities_fpx_payments: String
    capabilities_giropay_payments: String
    capabilities_grabpay_payments: String
    capabilities_ideal_payments: String
    capabilities_jcb_payments: String
    capabilities_legacy_payments: String
    capabilities_oxxo_payments: String
    capabilities_p24_payments: String
    capabilities_sepa_debit_payments: String
    capabilities_sofort_payments: String
    capabilities_tax_reporting_us_1099_k: String
    capabilities_tax_reporting_us_1099_misc: String
    capabilities_transfers: String
    company_address: JSON
    company_address_kana: JSON
    company_address_kanji: JSON
    company_directors_provided: Boolean
    company_executives_provided: Boolean
    company_name: String
    company_name_kana: String
    company_name_kanji: String
    company_owners_provided: Boolean
    company_phone: String
    company_structure: String
    company_tax_id_provided: Boolean
    company_tax_id_registrar: String
    company_vat_id_provided: Boolean
    company_verification: JSON
  }
`
