export const schema = gql`
  type Charge {
    id: String!
    amount: BigInt
    amount_captured: BigInt
    amount_refunded: BigInt
    application_id: String
    application_fee_id: String
    application_fee_amount: BigInt
    authorization_code: String
    balance_transaction_id: String
    calculated_statement_descriptor: String
    captured: Boolean
    created: DateTime
    currency: String
    customer_id: String
    description: String
    destination_id: String
    dispute_id: String
    disputed: Boolean
    failure_code: String
    failure_message: String
    invoice_id: String
    livemode: Boolean
    metadata: JSON
    object: String
    on_behalf_of_id: String
    order_id: String
    paid: Boolean
    payment_intent_id: String
    payment_method_id: String
    receipt_email: String
    receipt_number: String
    receipt_url: String
    refunded: Boolean
    review_id: String
    source_transfer_id: String
    statement_descriptor: String
    statement_descriptor_suffix: String
    status: String
    transfer_id: String
    transfer_group: String
    level3_customer_reference: String
    level3_line_items: JSON
    level3_merchant_reference: String
    level3_shipping_address_zip: String
    level3_shipping_amount: BigInt
    level3_shipping_from_zip: String
    shipping_address: JSON
    shipping_carrier: String
    shipping_name: String
    shipping_phone: String
    shipping_tracking_number: String
    fraud_details_stripe_report: String
    fraud_details_user_report: String
    transfer_data_amount: BigInt
    transfer_data_destination_id: String
    alternate_statement_descriptors_kana: String
    alternate_statement_descriptors_kanji: String
    payment_method_details_ach_credit_transfer: JSON
    payment_method_details_ach_debit: JSON
    payment_method_details_acss_debit: JSON
    payment_method_details_afterpay_clearpay: JSON
    payment_method_details_alipay: JSON
    payment_method_details_au_becs_debit: JSON
    payment_method_details_bacs_debit: JSON
    payment_method_details_bancontact: JSON
    payment_method_details_card: JSON
    payment_method_details_card_present: JSON
    payment_method_details_eps: JSON
    payment_method_details_fpx: JSON
    payment_method_details_giropay: JSON
    payment_method_details_grabpay: JSON
    payment_method_details_ideal: JSON
    payment_method_details_interac_present: JSON
    payment_method_details_klarna: JSON
    payment_method_details_multibanco: JSON
    payment_method_details_oxxo: JSON
    payment_method_details_p24: JSON
    payment_method_details_sepa_credit_transfer: JSON
    payment_method_details_sepa_debit: JSON
    payment_method_details_sofort: JSON
    payment_method_details_stripe_account: JSON
    payment_method_details_type: String
    payment_method_details_wechat: JSON
    billing_details_address: JSON
    billing_details_email: String
    billing_details_name: String
    billing_details_phone: String
    outcome_network_status: String
    outcome_reason: String
    outcome_risk_level: String
    outcome_risk_score: BigInt
    outcome_rule: JSON
    outcome_seller_message: String
    outcome_type: String
    application_fee_application_feeTocharge_application_fee_id: ApplicationFee
    application: Application
    balance_transaction: BalanceTransaction
    customer: Customer
    account_accountTocharge_destination_id: Account
    dispute_charge_dispute_idTodispute: Dispute
    invoice_charge_invoice_idToinvoice: Invoice
    account_accountTocharge_on_behalf_of_id: Account
    order_charge_order_idToorder: Order
    payment_intent: PaymentIntent
    payment_method: PaymentMethod
    review_charge_review_idToreview: Review
    transfer_charge_source_transfer_idTotransfer: Transfer
    account_accountTocharge_transfer_data_destination_id: Account
    transfer_charge_transfer_idTotransfer: Transfer
    application_fee_application_fee_charge_idTocharge: [ApplicationFee]!
    application_fee_application_fee_originating_transaction_idTocharge: [ApplicationFee]!
    dispute_chargeTodispute_charge_id: [Dispute]!
    invoice_chargeToinvoice_charge_id: [Invoice]!
    issuer_fraud_record: [IssuerFraudRecord]!
    order_chargeToorder_charge_id: [Order]!
    radar_early_fraud_warning: [RadarEarlyFraudWarning]!
    refund: [Refund]!
    review_chargeToreview_charge_id: [Review]!
    transfer_chargeTotransfer_destination_payment_id: [Transfer]!
    transfer_chargeTotransfer_source_transaction_id: [Transfer]!
  }

  type Query {
    charges: [Charge!]!
  }

  input CreateChargeInput {
    amount: BigInt
    amount_captured: BigInt
    amount_refunded: BigInt
    application_id: String
    application_fee_id: String
    application_fee_amount: BigInt
    authorization_code: String
    balance_transaction_id: String
    calculated_statement_descriptor: String
    captured: Boolean
    created: DateTime
    currency: String
    customer_id: String
    description: String
    destination_id: String
    dispute_id: String
    disputed: Boolean
    failure_code: String
    failure_message: String
    invoice_id: String
    livemode: Boolean
    metadata: JSON
    object: String
    on_behalf_of_id: String
    order_id: String
    paid: Boolean
    payment_intent_id: String
    payment_method_id: String
    receipt_email: String
    receipt_number: String
    receipt_url: String
    refunded: Boolean
    review_id: String
    source_transfer_id: String
    statement_descriptor: String
    statement_descriptor_suffix: String
    status: String
    transfer_id: String
    transfer_group: String
    level3_customer_reference: String
    level3_line_items: JSON
    level3_merchant_reference: String
    level3_shipping_address_zip: String
    level3_shipping_amount: BigInt
    level3_shipping_from_zip: String
    shipping_address: JSON
    shipping_carrier: String
    shipping_name: String
    shipping_phone: String
    shipping_tracking_number: String
    fraud_details_stripe_report: String
    fraud_details_user_report: String
    transfer_data_amount: BigInt
    transfer_data_destination_id: String
    alternate_statement_descriptors_kana: String
    alternate_statement_descriptors_kanji: String
    payment_method_details_ach_credit_transfer: JSON
    payment_method_details_ach_debit: JSON
    payment_method_details_acss_debit: JSON
    payment_method_details_afterpay_clearpay: JSON
    payment_method_details_alipay: JSON
    payment_method_details_au_becs_debit: JSON
    payment_method_details_bacs_debit: JSON
    payment_method_details_bancontact: JSON
    payment_method_details_card: JSON
    payment_method_details_card_present: JSON
    payment_method_details_eps: JSON
    payment_method_details_fpx: JSON
    payment_method_details_giropay: JSON
    payment_method_details_grabpay: JSON
    payment_method_details_ideal: JSON
    payment_method_details_interac_present: JSON
    payment_method_details_klarna: JSON
    payment_method_details_multibanco: JSON
    payment_method_details_oxxo: JSON
    payment_method_details_p24: JSON
    payment_method_details_sepa_credit_transfer: JSON
    payment_method_details_sepa_debit: JSON
    payment_method_details_sofort: JSON
    payment_method_details_stripe_account: JSON
    payment_method_details_type: String
    payment_method_details_wechat: JSON
    billing_details_address: JSON
    billing_details_email: String
    billing_details_name: String
    billing_details_phone: String
    outcome_network_status: String
    outcome_reason: String
    outcome_risk_level: String
    outcome_risk_score: BigInt
    outcome_rule: JSON
    outcome_seller_message: String
    outcome_type: String
  }

  input UpdateChargeInput {
    amount: BigInt
    amount_captured: BigInt
    amount_refunded: BigInt
    application_id: String
    application_fee_id: String
    application_fee_amount: BigInt
    authorization_code: String
    balance_transaction_id: String
    calculated_statement_descriptor: String
    captured: Boolean
    created: DateTime
    currency: String
    customer_id: String
    description: String
    destination_id: String
    dispute_id: String
    disputed: Boolean
    failure_code: String
    failure_message: String
    invoice_id: String
    livemode: Boolean
    metadata: JSON
    object: String
    on_behalf_of_id: String
    order_id: String
    paid: Boolean
    payment_intent_id: String
    payment_method_id: String
    receipt_email: String
    receipt_number: String
    receipt_url: String
    refunded: Boolean
    review_id: String
    source_transfer_id: String
    statement_descriptor: String
    statement_descriptor_suffix: String
    status: String
    transfer_id: String
    transfer_group: String
    level3_customer_reference: String
    level3_line_items: JSON
    level3_merchant_reference: String
    level3_shipping_address_zip: String
    level3_shipping_amount: BigInt
    level3_shipping_from_zip: String
    shipping_address: JSON
    shipping_carrier: String
    shipping_name: String
    shipping_phone: String
    shipping_tracking_number: String
    fraud_details_stripe_report: String
    fraud_details_user_report: String
    transfer_data_amount: BigInt
    transfer_data_destination_id: String
    alternate_statement_descriptors_kana: String
    alternate_statement_descriptors_kanji: String
    payment_method_details_ach_credit_transfer: JSON
    payment_method_details_ach_debit: JSON
    payment_method_details_acss_debit: JSON
    payment_method_details_afterpay_clearpay: JSON
    payment_method_details_alipay: JSON
    payment_method_details_au_becs_debit: JSON
    payment_method_details_bacs_debit: JSON
    payment_method_details_bancontact: JSON
    payment_method_details_card: JSON
    payment_method_details_card_present: JSON
    payment_method_details_eps: JSON
    payment_method_details_fpx: JSON
    payment_method_details_giropay: JSON
    payment_method_details_grabpay: JSON
    payment_method_details_ideal: JSON
    payment_method_details_interac_present: JSON
    payment_method_details_klarna: JSON
    payment_method_details_multibanco: JSON
    payment_method_details_oxxo: JSON
    payment_method_details_p24: JSON
    payment_method_details_sepa_credit_transfer: JSON
    payment_method_details_sepa_debit: JSON
    payment_method_details_sofort: JSON
    payment_method_details_stripe_account: JSON
    payment_method_details_type: String
    payment_method_details_wechat: JSON
    billing_details_address: JSON
    billing_details_email: String
    billing_details_name: String
    billing_details_phone: String
    outcome_network_status: String
    outcome_reason: String
    outcome_risk_level: String
    outcome_risk_score: BigInt
    outcome_rule: JSON
    outcome_seller_message: String
    outcome_type: String
  }
`
