export const schema = gql`
  type Dispute {
    id: String!
    amount: BigInt
    charge_id: String
    created: DateTime
    currency: String
    is_charge_refundable: Boolean
    livemode: Boolean
    metadata: JSON
    network_reason_code: String
    object: String
    payment_intent_id: String
    reason: String
    status: String
    evidence_access_activity_log: String
    evidence_billing_address: String
    evidence_cancellation_policy_id: String
    evidence_cancellation_policy_disclosure: String
    evidence_cancellation_rebuttal: String
    evidence_customer_communication_id: String
    evidence_customer_email_address: String
    evidence_customer_name: String
    evidence_customer_purchase_ip: String
    evidence_customer_signature_id: String
    evidence_duplicate_charge_documentation_id: String
    evidence_duplicate_charge_explanation: String
    evidence_duplicate_charge_id: String
    evidence_product_description: String
    evidence_receipt_id: String
    evidence_refund_policy_id: String
    evidence_refund_policy_disclosure: String
    evidence_refund_refusal_explanation: String
    evidence_service_date: String
    evidence_service_documentation_id: String
    evidence_shipping_address: String
    evidence_shipping_carrier: String
    evidence_shipping_date: String
    evidence_shipping_documentation_id: String
    evidence_shipping_tracking_number: String
    evidence_uncategorized_file_id: String
    evidence_uncategorized_text: String
    evidence_details_due_by: DateTime
    evidence_details_has_evidence: Boolean
    evidence_details_past_due: Boolean
    evidence_details_submission_count: BigInt
    charge_chargeTodispute_charge_id: Charge
    file_dispute_evidence_cancellation_policy_idTofile: File
    file_dispute_evidence_customer_communication_idTofile: File
    file_dispute_evidence_customer_signature_idTofile: File
    file_dispute_evidence_duplicate_charge_documentation_idTofile: File
    file_dispute_evidence_receipt_idTofile: File
    file_dispute_evidence_refund_policy_idTofile: File
    file_dispute_evidence_service_documentation_idTofile: File
    file_dispute_evidence_shipping_documentation_idTofile: File
    file_dispute_evidence_uncategorized_file_idTofile: File
    payment_intent: PaymentIntent
    charge_charge_dispute_idTodispute: [Charge]!
  }

  type Query {
    disputes: [Dispute!]!
  }

  input CreateDisputeInput {
    amount: BigInt
    charge_id: String
    created: DateTime
    currency: String
    is_charge_refundable: Boolean
    livemode: Boolean
    metadata: JSON
    network_reason_code: String
    object: String
    payment_intent_id: String
    reason: String
    status: String
    evidence_access_activity_log: String
    evidence_billing_address: String
    evidence_cancellation_policy_id: String
    evidence_cancellation_policy_disclosure: String
    evidence_cancellation_rebuttal: String
    evidence_customer_communication_id: String
    evidence_customer_email_address: String
    evidence_customer_name: String
    evidence_customer_purchase_ip: String
    evidence_customer_signature_id: String
    evidence_duplicate_charge_documentation_id: String
    evidence_duplicate_charge_explanation: String
    evidence_duplicate_charge_id: String
    evidence_product_description: String
    evidence_receipt_id: String
    evidence_refund_policy_id: String
    evidence_refund_policy_disclosure: String
    evidence_refund_refusal_explanation: String
    evidence_service_date: String
    evidence_service_documentation_id: String
    evidence_shipping_address: String
    evidence_shipping_carrier: String
    evidence_shipping_date: String
    evidence_shipping_documentation_id: String
    evidence_shipping_tracking_number: String
    evidence_uncategorized_file_id: String
    evidence_uncategorized_text: String
    evidence_details_due_by: DateTime
    evidence_details_has_evidence: Boolean
    evidence_details_past_due: Boolean
    evidence_details_submission_count: BigInt
  }

  input UpdateDisputeInput {
    amount: BigInt
    charge_id: String
    created: DateTime
    currency: String
    is_charge_refundable: Boolean
    livemode: Boolean
    metadata: JSON
    network_reason_code: String
    object: String
    payment_intent_id: String
    reason: String
    status: String
    evidence_access_activity_log: String
    evidence_billing_address: String
    evidence_cancellation_policy_id: String
    evidence_cancellation_policy_disclosure: String
    evidence_cancellation_rebuttal: String
    evidence_customer_communication_id: String
    evidence_customer_email_address: String
    evidence_customer_name: String
    evidence_customer_purchase_ip: String
    evidence_customer_signature_id: String
    evidence_duplicate_charge_documentation_id: String
    evidence_duplicate_charge_explanation: String
    evidence_duplicate_charge_id: String
    evidence_product_description: String
    evidence_receipt_id: String
    evidence_refund_policy_id: String
    evidence_refund_policy_disclosure: String
    evidence_refund_refusal_explanation: String
    evidence_service_date: String
    evidence_service_documentation_id: String
    evidence_shipping_address: String
    evidence_shipping_carrier: String
    evidence_shipping_date: String
    evidence_shipping_documentation_id: String
    evidence_shipping_tracking_number: String
    evidence_uncategorized_file_id: String
    evidence_uncategorized_text: String
    evidence_details_due_by: DateTime
    evidence_details_has_evidence: Boolean
    evidence_details_past_due: Boolean
    evidence_details_submission_count: BigInt
  }
`
