export const schema = gql`
  type Invoice {
    id: String!
    deleted: Boolean
    object: String
    account_country: String
    account_name: String
    account_tax_ids: [String]!
    amount_due: BigInt
    amount_paid: BigInt
    amount_remaining: BigInt
    application_fee_amount: BigInt
    attempt_count: BigInt
    attempted: Boolean
    auto_advance: Boolean
    billing_reason: String
    charge_id: String
    collection_method: String
    created: DateTime
    currency: String
    customer_id: String
    customer_email: String
    customer_name: String
    customer_phone: String
    customer_tax_exempt: String
    default_payment_method_id: String
    description: String
    discount_id: String
    discounts: [String]!
    due_date: DateTime
    ending_balance: BigInt
    footer: String
    hosted_invoice_url: String
    invoice_pdf: String
    livemode: Boolean
    metadata: JSON
    next_payment_attempt: DateTime
    number: String
    on_behalf_of_id: String
    paid: Boolean
    payment_intent_id: String
    period_end: DateTime
    period_start: DateTime
    post_payment_credit_notes_amount: BigInt
    pre_payment_credit_notes_amount: BigInt
    receipt_number: String
    starting_balance: BigInt
    statement_descriptor: String
    status: String
    subscription_id: String
    subscription_proration_date: BigInt
    subtotal: BigInt
    tax: BigInt
    total: BigInt
    webhooks_delivered_at: DateTime
    custom_fields_name: String
    custom_fields_value: String
    customer_shipping_address: JSON
    customer_shipping_carrier: String
    customer_shipping_name: String
    customer_shipping_phone: String
    customer_shipping_tracking_number: String
    payment_settings_payment_method_options: JSON
    payment_settings_payment_method_types: [String]!
    status_transitions_finalized_at: DateTime
    status_transitions_marked_uncollectible_at: DateTime
    status_transitions_paid_at: DateTime
    status_transitions_voided_at: DateTime
    total_discount_amounts_amount: BigInt
    total_discount_amounts_discount_id: String
    customer_address_city: String
    customer_address_country: String
    customer_address_line1: String
    customer_address_line2: String
    customer_address_postal_code: String
    customer_address_state: String
    last_finalization_error_charge: String
    last_finalization_error_code: String
    last_finalization_error_decline_code: String
    last_finalization_error_doc_url: String
    last_finalization_error_message: String
    last_finalization_error_param: String
    last_finalization_error_payment_intent_id: String
    last_finalization_error_payment_method_id: String
    last_finalization_error_payment_method_type: String
    last_finalization_error_setup_intent_id: String
    last_finalization_error_source: JSON
    last_finalization_error_type: String
    threshold_reason_amount_gte: BigInt
    threshold_reason_item_reasons: JSON
    total_tax_amounts_amount: BigInt
    total_tax_amounts_inclusive: Boolean
    total_tax_amounts_tax_rate_id: String
    customer_tax_ids_type: String
    customer_tax_ids_value: String
    transfer_data_amount: BigInt
    transfer_data_destination_id: String
    charge_chargeToinvoice_charge_id: Charge
    customer: Customer
    payment_method_invoice_default_payment_method_idTopayment_method: PaymentMethod
    discount_discountToinvoice_discount_id: Discount
    payment_intent_invoice_last_finalization_error_payment_intent_idTopayment_intent: PaymentIntent
    payment_method_invoice_last_finalization_error_payment_method_idTopayment_method: PaymentMethod
    setup_intent: SetupIntent
    account_accountToinvoice_on_behalf_of_id: Account
    payment_intent_invoice_payment_intent_idTopayment_intent: PaymentIntent
    subscription_invoice_subscription_idTosubscription: Subscription
    discount_discountToinvoice_total_discount_amounts_discount_id: Discount
    tax_rate: TaxRate
    account_accountToinvoice_transfer_data_destination_id: Account
    charge_charge_invoice_idToinvoice: [Charge]!
    credit_note: [CreditNote]!
    customer_balance_transaction: [CustomerBalanceTransaction]!
    discount_discount_invoice_idToinvoice: [Discount]!
    invoice_item: [InvoiceItem]!
    payment_intent_invoiceTopayment_intent_invoice_id: [PaymentIntent]!
    subscription_invoiceTosubscription_latest_invoice_id: [Subscription]!
    usage_record_summary: [UsageRecordSummary]!
  }

  type Query {
    invoices: [Invoice!]!
  }

  input CreateInvoiceInput {
    deleted: Boolean
    object: String
    account_country: String
    account_name: String
    account_tax_ids: [String]!
    amount_due: BigInt
    amount_paid: BigInt
    amount_remaining: BigInt
    application_fee_amount: BigInt
    attempt_count: BigInt
    attempted: Boolean
    auto_advance: Boolean
    billing_reason: String
    charge_id: String
    collection_method: String
    created: DateTime
    currency: String
    customer_id: String
    customer_email: String
    customer_name: String
    customer_phone: String
    customer_tax_exempt: String
    default_payment_method_id: String
    description: String
    discount_id: String
    discounts: [String]!
    due_date: DateTime
    ending_balance: BigInt
    footer: String
    hosted_invoice_url: String
    invoice_pdf: String
    livemode: Boolean
    metadata: JSON
    next_payment_attempt: DateTime
    number: String
    on_behalf_of_id: String
    paid: Boolean
    payment_intent_id: String
    period_end: DateTime
    period_start: DateTime
    post_payment_credit_notes_amount: BigInt
    pre_payment_credit_notes_amount: BigInt
    receipt_number: String
    starting_balance: BigInt
    statement_descriptor: String
    status: String
    subscription_id: String
    subscription_proration_date: BigInt
    subtotal: BigInt
    tax: BigInt
    total: BigInt
    webhooks_delivered_at: DateTime
    custom_fields_name: String
    custom_fields_value: String
    customer_shipping_address: JSON
    customer_shipping_carrier: String
    customer_shipping_name: String
    customer_shipping_phone: String
    customer_shipping_tracking_number: String
    payment_settings_payment_method_options: JSON
    payment_settings_payment_method_types: [String]!
    status_transitions_finalized_at: DateTime
    status_transitions_marked_uncollectible_at: DateTime
    status_transitions_paid_at: DateTime
    status_transitions_voided_at: DateTime
    total_discount_amounts_amount: BigInt
    total_discount_amounts_discount_id: String
    customer_address_city: String
    customer_address_country: String
    customer_address_line1: String
    customer_address_line2: String
    customer_address_postal_code: String
    customer_address_state: String
    last_finalization_error_charge: String
    last_finalization_error_code: String
    last_finalization_error_decline_code: String
    last_finalization_error_doc_url: String
    last_finalization_error_message: String
    last_finalization_error_param: String
    last_finalization_error_payment_intent_id: String
    last_finalization_error_payment_method_id: String
    last_finalization_error_payment_method_type: String
    last_finalization_error_setup_intent_id: String
    last_finalization_error_source: JSON
    last_finalization_error_type: String
    threshold_reason_amount_gte: BigInt
    threshold_reason_item_reasons: JSON
    total_tax_amounts_amount: BigInt
    total_tax_amounts_inclusive: Boolean
    total_tax_amounts_tax_rate_id: String
    customer_tax_ids_type: String
    customer_tax_ids_value: String
    transfer_data_amount: BigInt
    transfer_data_destination_id: String
  }

  input UpdateInvoiceInput {
    deleted: Boolean
    object: String
    account_country: String
    account_name: String
    account_tax_ids: [String]!
    amount_due: BigInt
    amount_paid: BigInt
    amount_remaining: BigInt
    application_fee_amount: BigInt
    attempt_count: BigInt
    attempted: Boolean
    auto_advance: Boolean
    billing_reason: String
    charge_id: String
    collection_method: String
    created: DateTime
    currency: String
    customer_id: String
    customer_email: String
    customer_name: String
    customer_phone: String
    customer_tax_exempt: String
    default_payment_method_id: String
    description: String
    discount_id: String
    discounts: [String]!
    due_date: DateTime
    ending_balance: BigInt
    footer: String
    hosted_invoice_url: String
    invoice_pdf: String
    livemode: Boolean
    metadata: JSON
    next_payment_attempt: DateTime
    number: String
    on_behalf_of_id: String
    paid: Boolean
    payment_intent_id: String
    period_end: DateTime
    period_start: DateTime
    post_payment_credit_notes_amount: BigInt
    pre_payment_credit_notes_amount: BigInt
    receipt_number: String
    starting_balance: BigInt
    statement_descriptor: String
    status: String
    subscription_id: String
    subscription_proration_date: BigInt
    subtotal: BigInt
    tax: BigInt
    total: BigInt
    webhooks_delivered_at: DateTime
    custom_fields_name: String
    custom_fields_value: String
    customer_shipping_address: JSON
    customer_shipping_carrier: String
    customer_shipping_name: String
    customer_shipping_phone: String
    customer_shipping_tracking_number: String
    payment_settings_payment_method_options: JSON
    payment_settings_payment_method_types: [String]!
    status_transitions_finalized_at: DateTime
    status_transitions_marked_uncollectible_at: DateTime
    status_transitions_paid_at: DateTime
    status_transitions_voided_at: DateTime
    total_discount_amounts_amount: BigInt
    total_discount_amounts_discount_id: String
    customer_address_city: String
    customer_address_country: String
    customer_address_line1: String
    customer_address_line2: String
    customer_address_postal_code: String
    customer_address_state: String
    last_finalization_error_charge: String
    last_finalization_error_code: String
    last_finalization_error_decline_code: String
    last_finalization_error_doc_url: String
    last_finalization_error_message: String
    last_finalization_error_param: String
    last_finalization_error_payment_intent_id: String
    last_finalization_error_payment_method_id: String
    last_finalization_error_payment_method_type: String
    last_finalization_error_setup_intent_id: String
    last_finalization_error_source: JSON
    last_finalization_error_type: String
    threshold_reason_amount_gte: BigInt
    threshold_reason_item_reasons: JSON
    total_tax_amounts_amount: BigInt
    total_tax_amounts_inclusive: Boolean
    total_tax_amounts_tax_rate_id: String
    customer_tax_ids_type: String
    customer_tax_ids_value: String
    transfer_data_amount: BigInt
    transfer_data_destination_id: String
  }
`
