export const schema = gql`
  type PaymentMethod {
    id: String!
    created: DateTime
    customer_id: String
    livemode: Boolean
    metadata: JSON
    object: String
    type: String
    sofort_country: String
    billing_details_address: JSON
    billing_details_email: String
    billing_details_name: String
    billing_details_phone: String
    bacs_debit_fingerprint: String
    bacs_debit_last4: String
    bacs_debit_sort_code: String
    eps_bank: String
    fpx_account_holder_type: String
    fpx_bank: String
    ideal_bank: String
    ideal_bic: String
    card_brand: String
    card_checks: JSON
    card_country: String
    card_description: String
    card_exp_month: BigInt
    card_exp_year: BigInt
    card_fingerprint: String
    card_funding: String
    card_iin: String
    card_issuer: String
    card_last4: String
    card_networks: JSON
    card_three_d_secure_usage: JSON
    card_wallet: JSON
    sepa_debit_bank_code: String
    sepa_debit_branch_code: String
    sepa_debit_country: String
    sepa_debit_fingerprint: String
    sepa_debit_generated_from: JSON
    sepa_debit_last4: String
    acss_debit_bank_name: String
    acss_debit_fingerprint: String
    acss_debit_institution_number: String
    acss_debit_last4: String
    acss_debit_transit_number: String
    au_becs_debit_bsb_number: String
    au_becs_debit_fingerprint: String
    au_becs_debit_last4: String
    p24_bank: String
    customer_customerTopayment_method_customer_id: Customer
    charge: [Charge]!
    customer_customer_invoice_settings_default_payment_method_idTopayment_method: [Customer]!
    invoice_invoice_default_payment_method_idTopayment_method: [Invoice]!
    invoice_invoice_last_finalization_error_payment_method_idTopayment_method: [Invoice]!
    mandate: [Mandate]!
    payment_intent_payment_intent_last_payment_error_payment_method_idTopayment_method: [PaymentIntent]!
    payment_intent_payment_intent_payment_method_idTopayment_method: [PaymentIntent]!
    setup_attempt_payment_methodTosetup_attempt_payment_method_id: [SetupAttempt]!
    setup_attempt_payment_methodTosetup_attempt_setup_error_payment_method_id: [SetupAttempt]!
    setup_intent_payment_methodTosetup_intent_last_setup_error_payment_method_id: [SetupIntent]!
    setup_intent_payment_methodTosetup_intent_payment_method_id: [SetupIntent]!
    subscription: [Subscription]!
    subscription_schedule_payment_methodTosubscription_schedule_default_settings_default_payment_method_id: [SubscriptionSchedule]!
    subscription_schedule_payment_methodTosubscription_schedule_phases_default_payment_method_id: [SubscriptionSchedule]!
  }

  type Query {
    paymentMethods: [PaymentMethod!]!
  }

  input CreatePaymentMethodInput {
    created: DateTime
    customer_id: String
    livemode: Boolean
    metadata: JSON
    object: String
    type: String
    sofort_country: String
    billing_details_address: JSON
    billing_details_email: String
    billing_details_name: String
    billing_details_phone: String
    bacs_debit_fingerprint: String
    bacs_debit_last4: String
    bacs_debit_sort_code: String
    eps_bank: String
    fpx_account_holder_type: String
    fpx_bank: String
    ideal_bank: String
    ideal_bic: String
    card_brand: String
    card_checks: JSON
    card_country: String
    card_description: String
    card_exp_month: BigInt
    card_exp_year: BigInt
    card_fingerprint: String
    card_funding: String
    card_iin: String
    card_issuer: String
    card_last4: String
    card_networks: JSON
    card_three_d_secure_usage: JSON
    card_wallet: JSON
    sepa_debit_bank_code: String
    sepa_debit_branch_code: String
    sepa_debit_country: String
    sepa_debit_fingerprint: String
    sepa_debit_generated_from: JSON
    sepa_debit_last4: String
    acss_debit_bank_name: String
    acss_debit_fingerprint: String
    acss_debit_institution_number: String
    acss_debit_last4: String
    acss_debit_transit_number: String
    au_becs_debit_bsb_number: String
    au_becs_debit_fingerprint: String
    au_becs_debit_last4: String
    p24_bank: String
  }

  input UpdatePaymentMethodInput {
    created: DateTime
    customer_id: String
    livemode: Boolean
    metadata: JSON
    object: String
    type: String
    sofort_country: String
    billing_details_address: JSON
    billing_details_email: String
    billing_details_name: String
    billing_details_phone: String
    bacs_debit_fingerprint: String
    bacs_debit_last4: String
    bacs_debit_sort_code: String
    eps_bank: String
    fpx_account_holder_type: String
    fpx_bank: String
    ideal_bank: String
    ideal_bic: String
    card_brand: String
    card_checks: JSON
    card_country: String
    card_description: String
    card_exp_month: BigInt
    card_exp_year: BigInt
    card_fingerprint: String
    card_funding: String
    card_iin: String
    card_issuer: String
    card_last4: String
    card_networks: JSON
    card_three_d_secure_usage: JSON
    card_wallet: JSON
    sepa_debit_bank_code: String
    sepa_debit_branch_code: String
    sepa_debit_country: String
    sepa_debit_fingerprint: String
    sepa_debit_generated_from: JSON
    sepa_debit_last4: String
    acss_debit_bank_name: String
    acss_debit_fingerprint: String
    acss_debit_institution_number: String
    acss_debit_last4: String
    acss_debit_transit_number: String
    au_becs_debit_bsb_number: String
    au_becs_debit_fingerprint: String
    au_becs_debit_last4: String
    p24_bank: String
  }
`
