export const schema = gql`
  type PaymentIntent {
    id: String!
    amount: BigInt
    amount_capturable: BigInt
    amount_received: BigInt
    application_id: String
    application_fee_amount: BigInt
    canceled_at: DateTime
    cancellation_reason: String
    capture_method: String
    client_secret: String
    confirmation_method: String
    created: DateTime
    currency: String
    customer_id: String
    description: String
    invoice_id: String
    livemode: Boolean
    metadata: JSON
    object: String
    on_behalf_of_id: String
    payment_method_id: String
    payment_method_types: [String]!
    receipt_email: String
    review_id: String
    setup_future_usage: String
    statement_descriptor: String
    statement_descriptor_suffix: String
    status: String
    transfer_group: String
    shipping_address: JSON
    shipping_carrier: String
    shipping_name: String
    shipping_phone: String
    shipping_tracking_number: String
    payment_method_options_acss_debit: JSON
    payment_method_options_afterpay_clearpay: JSON
    payment_method_options_alipay: JSON
    payment_method_options_bancontact: JSON
    payment_method_options_card: JSON
    payment_method_options_card_present: JSON
    payment_method_options_oxxo: JSON
    payment_method_options_p24: JSON
    payment_method_options_sepa_debit: JSON
    payment_method_options_sofort: JSON
    transfer_data_amount: BigInt
    transfer_data_destination_id: String
    last_payment_error_charge: String
    last_payment_error_code: String
    last_payment_error_decline_code: String
    last_payment_error_doc_url: String
    last_payment_error_message: String
    last_payment_error_param: String
    last_payment_error_payment_intent_id: String
    last_payment_error_payment_method_id: String
    last_payment_error_payment_method_type: String
    last_payment_error_setup_intent_id: String
    last_payment_error_source: JSON
    last_payment_error_type: String
    next_action_alipay_handle_redirect: JSON
    next_action_oxxo_display_details: JSON
    next_action_redirect_to_url: JSON
    next_action_type: String
    next_action_use_stripe_sdk: JSON
    next_action_verify_with_microdeposits: JSON
    application: Application
    customer: Customer
    invoice_invoiceTopayment_intent_invoice_id: Invoice
    payment_intent: PaymentIntent
    payment_method_payment_intent_last_payment_error_payment_method_idTopayment_method: PaymentMethod
    setup_intent_payment_intent_last_payment_error_setup_intent_idTosetup_intent: SetupIntent
    account_accountTopayment_intent_on_behalf_of_id: Account
    payment_method_payment_intent_payment_method_idTopayment_method: PaymentMethod
    review_payment_intent_review_idToreview: Review
    account_accountTopayment_intent_transfer_data_destination_id: Account
    charge: [Charge]!
    checkout_session: [CheckoutSession]!
    dispute: [Dispute]!
    invoice_invoice_last_finalization_error_payment_intent_idTopayment_intent: [Invoice]!
    invoice_invoice_payment_intent_idTopayment_intent: [Invoice]!
    other_payment_intent: [PaymentIntent]!
    radar_early_fraud_warning: [RadarEarlyFraudWarning]!
    refund: [Refund]!
    review_payment_intentToreview_payment_intent_id: [Review]!
    setup_attempt: [SetupAttempt]!
    setup_intent_payment_intentTosetup_intent_last_setup_error_payment_intent_id: [SetupIntent]!
  }

  type Query {
    paymentIntents: [PaymentIntent!]!
  }

  input CreatePaymentIntentInput {
    amount: BigInt
    amount_capturable: BigInt
    amount_received: BigInt
    application_id: String
    application_fee_amount: BigInt
    canceled_at: DateTime
    cancellation_reason: String
    capture_method: String
    client_secret: String
    confirmation_method: String
    created: DateTime
    currency: String
    customer_id: String
    description: String
    invoice_id: String
    livemode: Boolean
    metadata: JSON
    object: String
    on_behalf_of_id: String
    payment_method_id: String
    payment_method_types: [String]!
    receipt_email: String
    review_id: String
    setup_future_usage: String
    statement_descriptor: String
    statement_descriptor_suffix: String
    status: String
    transfer_group: String
    shipping_address: JSON
    shipping_carrier: String
    shipping_name: String
    shipping_phone: String
    shipping_tracking_number: String
    payment_method_options_acss_debit: JSON
    payment_method_options_afterpay_clearpay: JSON
    payment_method_options_alipay: JSON
    payment_method_options_bancontact: JSON
    payment_method_options_card: JSON
    payment_method_options_card_present: JSON
    payment_method_options_oxxo: JSON
    payment_method_options_p24: JSON
    payment_method_options_sepa_debit: JSON
    payment_method_options_sofort: JSON
    transfer_data_amount: BigInt
    transfer_data_destination_id: String
    last_payment_error_charge: String
    last_payment_error_code: String
    last_payment_error_decline_code: String
    last_payment_error_doc_url: String
    last_payment_error_message: String
    last_payment_error_param: String
    last_payment_error_payment_intent_id: String
    last_payment_error_payment_method_id: String
    last_payment_error_payment_method_type: String
    last_payment_error_setup_intent_id: String
    last_payment_error_source: JSON
    last_payment_error_type: String
    next_action_alipay_handle_redirect: JSON
    next_action_oxxo_display_details: JSON
    next_action_redirect_to_url: JSON
    next_action_type: String
    next_action_use_stripe_sdk: JSON
    next_action_verify_with_microdeposits: JSON
  }

  input UpdatePaymentIntentInput {
    amount: BigInt
    amount_capturable: BigInt
    amount_received: BigInt
    application_id: String
    application_fee_amount: BigInt
    canceled_at: DateTime
    cancellation_reason: String
    capture_method: String
    client_secret: String
    confirmation_method: String
    created: DateTime
    currency: String
    customer_id: String
    description: String
    invoice_id: String
    livemode: Boolean
    metadata: JSON
    object: String
    on_behalf_of_id: String
    payment_method_id: String
    payment_method_types: [String]!
    receipt_email: String
    review_id: String
    setup_future_usage: String
    statement_descriptor: String
    statement_descriptor_suffix: String
    status: String
    transfer_group: String
    shipping_address: JSON
    shipping_carrier: String
    shipping_name: String
    shipping_phone: String
    shipping_tracking_number: String
    payment_method_options_acss_debit: JSON
    payment_method_options_afterpay_clearpay: JSON
    payment_method_options_alipay: JSON
    payment_method_options_bancontact: JSON
    payment_method_options_card: JSON
    payment_method_options_card_present: JSON
    payment_method_options_oxxo: JSON
    payment_method_options_p24: JSON
    payment_method_options_sepa_debit: JSON
    payment_method_options_sofort: JSON
    transfer_data_amount: BigInt
    transfer_data_destination_id: String
    last_payment_error_charge: String
    last_payment_error_code: String
    last_payment_error_decline_code: String
    last_payment_error_doc_url: String
    last_payment_error_message: String
    last_payment_error_param: String
    last_payment_error_payment_intent_id: String
    last_payment_error_payment_method_id: String
    last_payment_error_payment_method_type: String
    last_payment_error_setup_intent_id: String
    last_payment_error_source: JSON
    last_payment_error_type: String
    next_action_alipay_handle_redirect: JSON
    next_action_oxxo_display_details: JSON
    next_action_redirect_to_url: JSON
    next_action_type: String
    next_action_use_stripe_sdk: JSON
    next_action_verify_with_microdeposits: JSON
  }
`
