export const schema = gql`
  type Person {
    id: String!
    deleted: Boolean
    object: String
    account_id: String
    created: DateTime
    email: String
    first_name: String
    first_name_kana: String
    first_name_kanji: String
    gender: String
    id_number_provided: Boolean
    last_name: String
    last_name_kana: String
    last_name_kanji: String
    maiden_name: String
    metadata: JSON
    nationality: String
    phone: String
    political_exposure: String
    ssn_last_4_provided: Boolean
    address_city: String
    address_country: String
    address_line1: String
    address_line2: String
    address_postal_code: String
    address_state: String
    relationship_director: Boolean
    relationship_executive: Boolean
    relationship_owner: Boolean
    relationship_percent_ownership: Decimal
    relationship_representative: Boolean
    relationship_title: String
    requirements_currently_due: [String]!
    requirements_errors: JSON
    requirements_eventually_due: [String]!
    requirements_past_due: [String]!
    requirements_pending_verification: [String]!
    address_kanji_city: String
    address_kanji_country: String
    address_kanji_line1: String
    address_kanji_line2: String
    address_kanji_postal_code: String
    address_kanji_state: String
    address_kanji_town: String
    address_kana_city: String
    address_kana_country: String
    address_kana_line1: String
    address_kana_line2: String
    address_kana_postal_code: String
    address_kana_state: String
    address_kana_town: String
    dob_day: BigInt
    dob_month: BigInt
    dob_year: BigInt
    verification_additional_document: JSON
    verification_details: String
    verification_details_code: String
    verification_document: JSON
    verification_status: String
    account_accountToperson_account_id: Account
    account_account_individual_idToperson: [Account]!
  }

  type Query {
    people: [Person!]!
  }

  input CreatePersonInput {
    deleted: Boolean
    object: String
    account_id: String
    created: DateTime
    email: String
    first_name: String
    first_name_kana: String
    first_name_kanji: String
    gender: String
    id_number_provided: Boolean
    last_name: String
    last_name_kana: String
    last_name_kanji: String
    maiden_name: String
    metadata: JSON
    nationality: String
    phone: String
    political_exposure: String
    ssn_last_4_provided: Boolean
    address_city: String
    address_country: String
    address_line1: String
    address_line2: String
    address_postal_code: String
    address_state: String
    relationship_director: Boolean
    relationship_executive: Boolean
    relationship_owner: Boolean
    relationship_percent_ownership: Decimal
    relationship_representative: Boolean
    relationship_title: String
    requirements_currently_due: [String]!
    requirements_errors: JSON
    requirements_eventually_due: [String]!
    requirements_past_due: [String]!
    requirements_pending_verification: [String]!
    address_kanji_city: String
    address_kanji_country: String
    address_kanji_line1: String
    address_kanji_line2: String
    address_kanji_postal_code: String
    address_kanji_state: String
    address_kanji_town: String
    address_kana_city: String
    address_kana_country: String
    address_kana_line1: String
    address_kana_line2: String
    address_kana_postal_code: String
    address_kana_state: String
    address_kana_town: String
    dob_day: BigInt
    dob_month: BigInt
    dob_year: BigInt
    verification_additional_document: JSON
    verification_details: String
    verification_details_code: String
    verification_document: JSON
    verification_status: String
  }

  input UpdatePersonInput {
    deleted: Boolean
    object: String
    account_id: String
    created: DateTime
    email: String
    first_name: String
    first_name_kana: String
    first_name_kanji: String
    gender: String
    id_number_provided: Boolean
    last_name: String
    last_name_kana: String
    last_name_kanji: String
    maiden_name: String
    metadata: JSON
    nationality: String
    phone: String
    political_exposure: String
    ssn_last_4_provided: Boolean
    address_city: String
    address_country: String
    address_line1: String
    address_line2: String
    address_postal_code: String
    address_state: String
    relationship_director: Boolean
    relationship_executive: Boolean
    relationship_owner: Boolean
    relationship_percent_ownership: Decimal
    relationship_representative: Boolean
    relationship_title: String
    requirements_currently_due: [String]!
    requirements_errors: JSON
    requirements_eventually_due: [String]!
    requirements_past_due: [String]!
    requirements_pending_verification: [String]!
    address_kanji_city: String
    address_kanji_country: String
    address_kanji_line1: String
    address_kanji_line2: String
    address_kanji_postal_code: String
    address_kanji_state: String
    address_kanji_town: String
    address_kana_city: String
    address_kana_country: String
    address_kana_line1: String
    address_kana_line2: String
    address_kana_postal_code: String
    address_kana_state: String
    address_kana_town: String
    dob_day: BigInt
    dob_month: BigInt
    dob_year: BigInt
    verification_additional_document: JSON
    verification_details: String
    verification_details_code: String
    verification_document: JSON
    verification_status: String
  }
`
