export const schema = gql`
  type Source {
    id: String!
    amount: BigInt
    client_secret: String
    created: DateTime
    currency: String
    customer_id: String
    flow: String
    livemode: Boolean
    metadata: JSON
    object: String
    statement_descriptor: String
    status: String
    type: String
    usage: String
    redirect_failure_reason: String
    redirect_return_url: String
    redirect_status: String
    redirect_url: String
    sofort_bank_code: String
    sofort_bank_name: String
    sofort_bic: String
    sofort_country: String
    sofort_iban_last4: String
    sofort_preferred_language: String
    sofort_statement_descriptor: String
    receiver_address: String
    receiver_amount_charged: BigInt
    receiver_amount_received: BigInt
    receiver_amount_returned: BigInt
    receiver_refund_attributes_method: String
    receiver_refund_attributes_status: String
    ach_credit_transfer_account_number: String
    ach_credit_transfer_bank_name: String
    ach_credit_transfer_fingerprint: String
    ach_credit_transfer_refund_account_holder_name: String
    ach_credit_transfer_refund_account_holder_type: String
    ach_credit_transfer_refund_routing_number: String
    ach_credit_transfer_routing_number: String
    ach_credit_transfer_swift_code: String
    au_becs_debit_bsb_number: String
    au_becs_debit_fingerprint: String
    au_becs_debit_last4: String
    sepa_debit_bank_code: String
    sepa_debit_branch_code: String
    sepa_debit_country: String
    sepa_debit_fingerprint: String
    sepa_debit_last4: String
    sepa_debit_mandate_reference: String
    sepa_debit_mandate_url: String
    owner_address: JSON
    owner_email: String
    owner_name: String
    owner_phone: String
    owner_verified_address: JSON
    owner_verified_email: String
    owner_verified_name: String
    owner_verified_phone: String
    p24_reference: String
    multibanco_entity: String
    multibanco_reference: String
    multibanco_refund_account_holder_address_city: String
    multibanco_refund_account_holder_address_country: String
    multibanco_refund_account_holder_address_line1: String
    multibanco_refund_account_holder_address_line2: String
    multibanco_refund_account_holder_address_postal_code: String
    multibanco_refund_account_holder_address_state: String
    multibanco_refund_account_holder_name: String
    multibanco_refund_iban: String
    source_order_amount: BigInt
    source_order_currency: String
    source_order_email: String
    source_order_items: JSON
    source_order_shipping: JSON
    card_present_application_cryptogram: String
    card_present_application_preferred_name: String
    card_present_authorization_code: String
    card_present_authorization_response_code: String
    card_present_brand: String
    card_present_country: String
    card_present_cvm_type: String
    card_present_data_type: String
    card_present_dedicated_file_name: String
    card_present_description: String
    card_present_emv_auth_data: String
    card_present_evidence_customer_signature: String
    card_present_evidence_transaction_certificate: String
    card_present_exp_month: BigInt
    card_present_exp_year: BigInt
    card_present_fingerprint: String
    card_present_funding: String
    card_present_iin: String
    card_present_issuer: String
    card_present_last4: String
    card_present_pos_device_id: String
    card_present_pos_entry_mode: String
    card_present_read_method: String
    card_present_reader: String
    card_present_terminal_verification_results: String
    card_present_transaction_status_information: String
    sepa_credit_transfer_bank_name: String
    sepa_credit_transfer_bic: String
    sepa_credit_transfer_iban: String
    sepa_credit_transfer_refund_account_holder_address_city: String
    sepa_credit_transfer_refund_account_holder_address_country: String
    sepa_credit_transfer_refund_account_holder_address_line1: String
    sepa_credit_transfer_refund_account_holder_address_line2: String
    sepa_credit_transfer_refund_account_holder_address_postal_code: String
    sepa_credit_transfer_refund_account_holder_address_state: String
    sepa_credit_transfer_refund_account_holder_name: String
    sepa_credit_transfer_refund_iban: String
    card_address_line1_check: String
    card_address_zip_check: String
    card_brand: String
    card_country: String
    card_cvc_check: String
    card_description: String
    card_dynamic_last4: String
    card_exp_month: BigInt
    card_exp_year: BigInt
    card_fingerprint: String
    card_funding: String
    card_iin: String
    card_issuer: String
    card_last4: String
    card_name: String
    card_three_d_secure: String
    card_tokenization_method: String
    klarna_background_image_url: String
    klarna_client_token: String
    klarna_first_name: String
    klarna_last_name: String
    klarna_locale: String
    klarna_logo_url: String
    klarna_page_title: String
    klarna_pay_later_asset_urls_descriptive: String
    klarna_pay_later_asset_urls_standard: String
    klarna_pay_later_name: String
    klarna_pay_later_redirect_url: String
    klarna_pay_now_asset_urls_descriptive: String
    klarna_pay_now_asset_urls_standard: String
    klarna_pay_now_name: String
    klarna_pay_now_redirect_url: String
    klarna_pay_over_time_asset_urls_descriptive: String
    klarna_pay_over_time_asset_urls_standard: String
    klarna_pay_over_time_name: String
    klarna_pay_over_time_redirect_url: String
    klarna_payment_method_categories: String
    klarna_purchase_country: String
    klarna_purchase_type: String
    klarna_redirect_url: String
    klarna_shipping_delay: BigInt
    klarna_shipping_first_name: String
    klarna_shipping_last_name: String
    ach_debit_bank_name: String
    ach_debit_country: String
    ach_debit_fingerprint: String
    ach_debit_last4: String
    ach_debit_routing_number: String
    ach_debit_type: String
    giropay_bank_code: String
    giropay_bank_name: String
    giropay_bic: String
    giropay_statement_descriptor: String
    acss_debit_bank_address_city: String
    acss_debit_bank_address_line_1: String
    acss_debit_bank_address_line_2: String
    acss_debit_bank_address_postal_code: String
    acss_debit_bank_name: String
    acss_debit_category: String
    acss_debit_country: String
    acss_debit_fingerprint: String
    acss_debit_last4: String
    acss_debit_routing_number: String
    code_verification_attempts_remaining: BigInt
    code_verification_status: String
    ideal_bank: String
    ideal_bic: String
    ideal_iban_last4: String
    ideal_statement_descriptor: String
    alipay_data_string: String
    alipay_native_url: String
    alipay_statement_descriptor: String
    eps_reference: String
    eps_statement_descriptor: String
    wechat_prepay_id: String
    wechat_qr_code_url: String
    wechat_statement_descriptor: String
    three_d_secure_address_line1_check: String
    three_d_secure_address_zip_check: String
    three_d_secure_authenticated: Boolean
    three_d_secure_brand: String
    three_d_secure_card: String
    three_d_secure_country: String
    three_d_secure_customer: String
    three_d_secure_cvc_check: String
    three_d_secure_description: String
    three_d_secure_dynamic_last4: String
    three_d_secure_exp_month: BigInt
    three_d_secure_exp_year: BigInt
    three_d_secure_fingerprint: String
    three_d_secure_funding: String
    three_d_secure_iin: String
    three_d_secure_issuer: String
    three_d_secure_last4: String
    three_d_secure_name: String
    three_d_secure_three_d_secure: String
    three_d_secure_tokenization_method: String
    bancontact_bank_code: String
    bancontact_bank_name: String
    bancontact_bic: String
    bancontact_iban_last4: String
    bancontact_preferred_language: String
    bancontact_statement_descriptor: String
    customer: Customer
    source_mandate_notification: [SourceMandateNotification]!
    source_transaction: [SourceTransaction]!
    topup: [Topup]!
  }

  type Query {
    sources: [Source!]!
  }

  input CreateSourceInput {
    amount: BigInt
    client_secret: String
    created: DateTime
    currency: String
    customer_id: String
    flow: String
    livemode: Boolean
    metadata: JSON
    object: String
    statement_descriptor: String
    status: String
    type: String
    usage: String
    redirect_failure_reason: String
    redirect_return_url: String
    redirect_status: String
    redirect_url: String
    sofort_bank_code: String
    sofort_bank_name: String
    sofort_bic: String
    sofort_country: String
    sofort_iban_last4: String
    sofort_preferred_language: String
    sofort_statement_descriptor: String
    receiver_address: String
    receiver_amount_charged: BigInt
    receiver_amount_received: BigInt
    receiver_amount_returned: BigInt
    receiver_refund_attributes_method: String
    receiver_refund_attributes_status: String
    ach_credit_transfer_account_number: String
    ach_credit_transfer_bank_name: String
    ach_credit_transfer_fingerprint: String
    ach_credit_transfer_refund_account_holder_name: String
    ach_credit_transfer_refund_account_holder_type: String
    ach_credit_transfer_refund_routing_number: String
    ach_credit_transfer_routing_number: String
    ach_credit_transfer_swift_code: String
    au_becs_debit_bsb_number: String
    au_becs_debit_fingerprint: String
    au_becs_debit_last4: String
    sepa_debit_bank_code: String
    sepa_debit_branch_code: String
    sepa_debit_country: String
    sepa_debit_fingerprint: String
    sepa_debit_last4: String
    sepa_debit_mandate_reference: String
    sepa_debit_mandate_url: String
    owner_address: JSON
    owner_email: String
    owner_name: String
    owner_phone: String
    owner_verified_address: JSON
    owner_verified_email: String
    owner_verified_name: String
    owner_verified_phone: String
    p24_reference: String
    multibanco_entity: String
    multibanco_reference: String
    multibanco_refund_account_holder_address_city: String
    multibanco_refund_account_holder_address_country: String
    multibanco_refund_account_holder_address_line1: String
    multibanco_refund_account_holder_address_line2: String
    multibanco_refund_account_holder_address_postal_code: String
    multibanco_refund_account_holder_address_state: String
    multibanco_refund_account_holder_name: String
    multibanco_refund_iban: String
    source_order_amount: BigInt
    source_order_currency: String
    source_order_email: String
    source_order_items: JSON
    source_order_shipping: JSON
    card_present_application_cryptogram: String
    card_present_application_preferred_name: String
    card_present_authorization_code: String
    card_present_authorization_response_code: String
    card_present_brand: String
    card_present_country: String
    card_present_cvm_type: String
    card_present_data_type: String
    card_present_dedicated_file_name: String
    card_present_description: String
    card_present_emv_auth_data: String
    card_present_evidence_customer_signature: String
    card_present_evidence_transaction_certificate: String
    card_present_exp_month: BigInt
    card_present_exp_year: BigInt
    card_present_fingerprint: String
    card_present_funding: String
    card_present_iin: String
    card_present_issuer: String
    card_present_last4: String
    card_present_pos_device_id: String
    card_present_pos_entry_mode: String
    card_present_read_method: String
    card_present_reader: String
    card_present_terminal_verification_results: String
    card_present_transaction_status_information: String
    sepa_credit_transfer_bank_name: String
    sepa_credit_transfer_bic: String
    sepa_credit_transfer_iban: String
    sepa_credit_transfer_refund_account_holder_address_city: String
    sepa_credit_transfer_refund_account_holder_address_country: String
    sepa_credit_transfer_refund_account_holder_address_line1: String
    sepa_credit_transfer_refund_account_holder_address_line2: String
    sepa_credit_transfer_refund_account_holder_address_postal_code: String
    sepa_credit_transfer_refund_account_holder_address_state: String
    sepa_credit_transfer_refund_account_holder_name: String
    sepa_credit_transfer_refund_iban: String
    card_address_line1_check: String
    card_address_zip_check: String
    card_brand: String
    card_country: String
    card_cvc_check: String
    card_description: String
    card_dynamic_last4: String
    card_exp_month: BigInt
    card_exp_year: BigInt
    card_fingerprint: String
    card_funding: String
    card_iin: String
    card_issuer: String
    card_last4: String
    card_name: String
    card_three_d_secure: String
    card_tokenization_method: String
    klarna_background_image_url: String
    klarna_client_token: String
    klarna_first_name: String
    klarna_last_name: String
    klarna_locale: String
    klarna_logo_url: String
    klarna_page_title: String
    klarna_pay_later_asset_urls_descriptive: String
    klarna_pay_later_asset_urls_standard: String
    klarna_pay_later_name: String
    klarna_pay_later_redirect_url: String
    klarna_pay_now_asset_urls_descriptive: String
    klarna_pay_now_asset_urls_standard: String
    klarna_pay_now_name: String
    klarna_pay_now_redirect_url: String
    klarna_pay_over_time_asset_urls_descriptive: String
    klarna_pay_over_time_asset_urls_standard: String
    klarna_pay_over_time_name: String
    klarna_pay_over_time_redirect_url: String
    klarna_payment_method_categories: String
    klarna_purchase_country: String
    klarna_purchase_type: String
    klarna_redirect_url: String
    klarna_shipping_delay: BigInt
    klarna_shipping_first_name: String
    klarna_shipping_last_name: String
    ach_debit_bank_name: String
    ach_debit_country: String
    ach_debit_fingerprint: String
    ach_debit_last4: String
    ach_debit_routing_number: String
    ach_debit_type: String
    giropay_bank_code: String
    giropay_bank_name: String
    giropay_bic: String
    giropay_statement_descriptor: String
    acss_debit_bank_address_city: String
    acss_debit_bank_address_line_1: String
    acss_debit_bank_address_line_2: String
    acss_debit_bank_address_postal_code: String
    acss_debit_bank_name: String
    acss_debit_category: String
    acss_debit_country: String
    acss_debit_fingerprint: String
    acss_debit_last4: String
    acss_debit_routing_number: String
    code_verification_attempts_remaining: BigInt
    code_verification_status: String
    ideal_bank: String
    ideal_bic: String
    ideal_iban_last4: String
    ideal_statement_descriptor: String
    alipay_data_string: String
    alipay_native_url: String
    alipay_statement_descriptor: String
    eps_reference: String
    eps_statement_descriptor: String
    wechat_prepay_id: String
    wechat_qr_code_url: String
    wechat_statement_descriptor: String
    three_d_secure_address_line1_check: String
    three_d_secure_address_zip_check: String
    three_d_secure_authenticated: Boolean
    three_d_secure_brand: String
    three_d_secure_card: String
    three_d_secure_country: String
    three_d_secure_customer: String
    three_d_secure_cvc_check: String
    three_d_secure_description: String
    three_d_secure_dynamic_last4: String
    three_d_secure_exp_month: BigInt
    three_d_secure_exp_year: BigInt
    three_d_secure_fingerprint: String
    three_d_secure_funding: String
    three_d_secure_iin: String
    three_d_secure_issuer: String
    three_d_secure_last4: String
    three_d_secure_name: String
    three_d_secure_three_d_secure: String
    three_d_secure_tokenization_method: String
    bancontact_bank_code: String
    bancontact_bank_name: String
    bancontact_bic: String
    bancontact_iban_last4: String
    bancontact_preferred_language: String
    bancontact_statement_descriptor: String
  }

  input UpdateSourceInput {
    amount: BigInt
    client_secret: String
    created: DateTime
    currency: String
    customer_id: String
    flow: String
    livemode: Boolean
    metadata: JSON
    object: String
    statement_descriptor: String
    status: String
    type: String
    usage: String
    redirect_failure_reason: String
    redirect_return_url: String
    redirect_status: String
    redirect_url: String
    sofort_bank_code: String
    sofort_bank_name: String
    sofort_bic: String
    sofort_country: String
    sofort_iban_last4: String
    sofort_preferred_language: String
    sofort_statement_descriptor: String
    receiver_address: String
    receiver_amount_charged: BigInt
    receiver_amount_received: BigInt
    receiver_amount_returned: BigInt
    receiver_refund_attributes_method: String
    receiver_refund_attributes_status: String
    ach_credit_transfer_account_number: String
    ach_credit_transfer_bank_name: String
    ach_credit_transfer_fingerprint: String
    ach_credit_transfer_refund_account_holder_name: String
    ach_credit_transfer_refund_account_holder_type: String
    ach_credit_transfer_refund_routing_number: String
    ach_credit_transfer_routing_number: String
    ach_credit_transfer_swift_code: String
    au_becs_debit_bsb_number: String
    au_becs_debit_fingerprint: String
    au_becs_debit_last4: String
    sepa_debit_bank_code: String
    sepa_debit_branch_code: String
    sepa_debit_country: String
    sepa_debit_fingerprint: String
    sepa_debit_last4: String
    sepa_debit_mandate_reference: String
    sepa_debit_mandate_url: String
    owner_address: JSON
    owner_email: String
    owner_name: String
    owner_phone: String
    owner_verified_address: JSON
    owner_verified_email: String
    owner_verified_name: String
    owner_verified_phone: String
    p24_reference: String
    multibanco_entity: String
    multibanco_reference: String
    multibanco_refund_account_holder_address_city: String
    multibanco_refund_account_holder_address_country: String
    multibanco_refund_account_holder_address_line1: String
    multibanco_refund_account_holder_address_line2: String
    multibanco_refund_account_holder_address_postal_code: String
    multibanco_refund_account_holder_address_state: String
    multibanco_refund_account_holder_name: String
    multibanco_refund_iban: String
    source_order_amount: BigInt
    source_order_currency: String
    source_order_email: String
    source_order_items: JSON
    source_order_shipping: JSON
    card_present_application_cryptogram: String
    card_present_application_preferred_name: String
    card_present_authorization_code: String
    card_present_authorization_response_code: String
    card_present_brand: String
    card_present_country: String
    card_present_cvm_type: String
    card_present_data_type: String
    card_present_dedicated_file_name: String
    card_present_description: String
    card_present_emv_auth_data: String
    card_present_evidence_customer_signature: String
    card_present_evidence_transaction_certificate: String
    card_present_exp_month: BigInt
    card_present_exp_year: BigInt
    card_present_fingerprint: String
    card_present_funding: String
    card_present_iin: String
    card_present_issuer: String
    card_present_last4: String
    card_present_pos_device_id: String
    card_present_pos_entry_mode: String
    card_present_read_method: String
    card_present_reader: String
    card_present_terminal_verification_results: String
    card_present_transaction_status_information: String
    sepa_credit_transfer_bank_name: String
    sepa_credit_transfer_bic: String
    sepa_credit_transfer_iban: String
    sepa_credit_transfer_refund_account_holder_address_city: String
    sepa_credit_transfer_refund_account_holder_address_country: String
    sepa_credit_transfer_refund_account_holder_address_line1: String
    sepa_credit_transfer_refund_account_holder_address_line2: String
    sepa_credit_transfer_refund_account_holder_address_postal_code: String
    sepa_credit_transfer_refund_account_holder_address_state: String
    sepa_credit_transfer_refund_account_holder_name: String
    sepa_credit_transfer_refund_iban: String
    card_address_line1_check: String
    card_address_zip_check: String
    card_brand: String
    card_country: String
    card_cvc_check: String
    card_description: String
    card_dynamic_last4: String
    card_exp_month: BigInt
    card_exp_year: BigInt
    card_fingerprint: String
    card_funding: String
    card_iin: String
    card_issuer: String
    card_last4: String
    card_name: String
    card_three_d_secure: String
    card_tokenization_method: String
    klarna_background_image_url: String
    klarna_client_token: String
    klarna_first_name: String
    klarna_last_name: String
    klarna_locale: String
    klarna_logo_url: String
    klarna_page_title: String
    klarna_pay_later_asset_urls_descriptive: String
    klarna_pay_later_asset_urls_standard: String
    klarna_pay_later_name: String
    klarna_pay_later_redirect_url: String
    klarna_pay_now_asset_urls_descriptive: String
    klarna_pay_now_asset_urls_standard: String
    klarna_pay_now_name: String
    klarna_pay_now_redirect_url: String
    klarna_pay_over_time_asset_urls_descriptive: String
    klarna_pay_over_time_asset_urls_standard: String
    klarna_pay_over_time_name: String
    klarna_pay_over_time_redirect_url: String
    klarna_payment_method_categories: String
    klarna_purchase_country: String
    klarna_purchase_type: String
    klarna_redirect_url: String
    klarna_shipping_delay: BigInt
    klarna_shipping_first_name: String
    klarna_shipping_last_name: String
    ach_debit_bank_name: String
    ach_debit_country: String
    ach_debit_fingerprint: String
    ach_debit_last4: String
    ach_debit_routing_number: String
    ach_debit_type: String
    giropay_bank_code: String
    giropay_bank_name: String
    giropay_bic: String
    giropay_statement_descriptor: String
    acss_debit_bank_address_city: String
    acss_debit_bank_address_line_1: String
    acss_debit_bank_address_line_2: String
    acss_debit_bank_address_postal_code: String
    acss_debit_bank_name: String
    acss_debit_category: String
    acss_debit_country: String
    acss_debit_fingerprint: String
    acss_debit_last4: String
    acss_debit_routing_number: String
    code_verification_attempts_remaining: BigInt
    code_verification_status: String
    ideal_bank: String
    ideal_bic: String
    ideal_iban_last4: String
    ideal_statement_descriptor: String
    alipay_data_string: String
    alipay_native_url: String
    alipay_statement_descriptor: String
    eps_reference: String
    eps_statement_descriptor: String
    wechat_prepay_id: String
    wechat_qr_code_url: String
    wechat_statement_descriptor: String
    three_d_secure_address_line1_check: String
    three_d_secure_address_zip_check: String
    three_d_secure_authenticated: Boolean
    three_d_secure_brand: String
    three_d_secure_card: String
    three_d_secure_country: String
    three_d_secure_customer: String
    three_d_secure_cvc_check: String
    three_d_secure_description: String
    three_d_secure_dynamic_last4: String
    three_d_secure_exp_month: BigInt
    three_d_secure_exp_year: BigInt
    three_d_secure_fingerprint: String
    three_d_secure_funding: String
    three_d_secure_iin: String
    three_d_secure_issuer: String
    three_d_secure_last4: String
    three_d_secure_name: String
    three_d_secure_three_d_secure: String
    three_d_secure_tokenization_method: String
    bancontact_bank_code: String
    bancontact_bank_name: String
    bancontact_bic: String
    bancontact_iban_last4: String
    bancontact_preferred_language: String
    bancontact_statement_descriptor: String
  }
`
